oro_permissions:
    DELETE:
        exclude_entities:
            - Effiana\TestFrameworkBundle\Entity\TestActivity

    ASSIGN:
        exclude_entities:
            - Effiana\TestFrameworkBundle\Entity\TestActivity
